### ISSUE TITLE
Incorporate feedback from discussion

### ISSUE THREAD

**Issue by jonaschn** [jonaschn/tuk-power#10]
- [x] signed integers as data types
- [x] non-zero initialization
- [x] flush cache
- [x] multiple runs (ignore first run)
- [x] Verify that a single large column scan is the same as scanning a single column of a large database in terms of performance

**Comment by flxw** [comment]
We could think about using OpenMP for multithreading. It is one of the fastest threading libraries around. Nicely done so far @danthe96 :)

**Comment by flxw** [comment]
uint64_t start_index = 0;
        for(int j=0;j < thread_count;j++){
            uint64_t end_index = start_index + part_len + (j < overhang ? 1 : 0);
            auto thread = new std::thread(thread_func<T>, std::ref(attribute_vector), col_count, start_index, end_index);
            threads.push_back(thread);
            start_index = end_index;
        }

        for(std::thread* thread: threads)
            (*thread).join();

        auto end = std::chrono::high_resolution_clock::now();
        auto time = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start);
        times.push_back(time.count());
        `threads.clear();
https://github.com/jonaschn/tuk-power/blob/master/benchmark/main.cpp#L61

Doesn't this leak memory or is the auto pointer one of those self-deleting ones?

**Comment by danthe96** [comment]
Good point, it's not a smart pointer so seems like a memory leak. This should fix it instead of `threads.clear()`:
```
while(!threads.empty())
    delete *(threads.pop());
```
