### ISSUE TITLE
Configure hyperthreading for intel machine

### ISSUE THREAD

**Issue by janetzki** [jonaschn/tuk-power#19]
Execute the benchmarks with all possible settings, e.g, 1, 2, 4 threads per physical core.

**Comment by MasterCarl** [comment]
I think it only makes sense to run two threads per core because our machine doesn't support more

**Comment by janetzki** [comment]
Are you sure? In this case, we would either use the current setting or turn the hyperthreading off to prevent other threads from running on the same physical core.
