### ISSUE TITLE
Improve the plots

### ISSUE THREAD

**Issue by janetzki** [jonaschn/tuk-power#23]
- [x] Cut off the beginning zero line
- [x] Add a caption
- [x] Add a flag to turn variance on/off
- [x] Add a flag to only show int64
- [x] No power in x axis labels
- [x] Check cache sizes POWER
- [x] Check cache sizes INTEL
- [x] Improve flag system

**Comment by ArneMayer** [comment]
#30

**Comment by jonaschn** [comment]
Flag system should be improved.
system_type should be a flag as well.
help flag would be also useful. 
```
    path = sys.argv[1] if len(sys.argv) > 1 else 'benchmark.csv'
    system_type = sys.argv[2] if len(sys.argv) > 2 else 'power'
    flags = sys.argv[3:]
    show_variance = 'no-variance' not in flags
    only_64 = 'only-64' in flags
```

**Comment by jonaschn** [comment]
#48
