### ISSUE TITLE
Fix caching/nocaching benchmarks for Intel machine

### ISSUE THREAD

**Issue by janetzki** [jonaschn/tuk-power#25]
They do not show the expected trend:
- Some caching benchmarks still have an increasing bandwidth beyond the L3 cache size.
- Some nocaching benchmarks drop after they pass a cache size.

It should be the other way around, as in the Power benchmarks.

**Comment by jonaschn** [comment]
@janetzki is this task still necessary?

**Comment by janetzki** [comment]
@jonaschn Yes, I am still looking into it.
I also narrowed down the question. Maybe executing the benchmarks again will fix this issue.

**Comment by janetzki** [comment]
The last benchmarks showed the expected behavior for caching. Since we do not execute benchmarks without caching anymore, this issue can be closed.
