### ISSUE TITLE
Evaluate how much thread execution times overlap

### ISSUE THREAD

**Issue by janetzki** [jonaschn/tuk-power#61]

**Comment by MasterCarl** [comment]
See branch `thread-times`

**Comment by MasterCarl** [comment]
For small sizes (8KB in intel-results/benchmark-cache-prefetch1-smt2-thread30-64bit.csv), the first thread does indeed end 3947 duration units, probably nanoseconds, **before the last thread starts**. This is probably mostly due to SMT.

**Comment by MasterCarl** [comment]
Without SMT, for 8MB, the time between first and last thread start is 4064 [ns]

**Comment by MasterCarl** [comment]
The time difference in `benchmark-nocache-prefetch1-smt1-thread15-64bit.csv` is 13.345 **ms** for 4GB.
