### ISSUE TITLE
Finalize presentation

### ISSUE THREAD

**Issue by jonaschn** [jonaschn/tuk-power#82]
- [x] More up-to-date performance graph (Slide 2)
- [x] Update Slide master (remove speaker, date, etc.) Just keep slide number.
- [x] Improve cache line animation (Slide 5)
- [ ] Document prefetcher settings (DSCR values)
- [x] Dashed lines for row-/colstore without prefetching (Slide 7)
- [x] Don't use comma, replace B (Slide 11)
- [x] Insert Multi-threading (without SMT)
- [x] Use darker color for cache sizes and cache labels
- [x] Use dashed lines and only two colors for lines (Slide 7 and 8)
- [x] Use bar chart instead of table (Slide 16)
- [x] #80 
- [x] Improve styling and slide master

**Comment by flxw** [comment]
Redeanteile:
Intro, Folie 1+2: Felix
3-9: Daniel
10-Ende: Felix
