### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by jonaschn** [jonaschn/tuk-power#99]
- [x] Bandwidth vs. Throughput

- [x] Update intel graphs (preprocessing: lines and legend should be consistent with POWER)

- [x] Update power graphs

- [x] Update agenda (on the right side to reflect parameter settings after topic was discussed)

- [x] Check if other parameters like column count or prefetch settings are documented

- [x] Fix summary slide (diagram)

- [x] Update perf stat (should be consistent, see POWER data PR)

- [x] Check if complete feedback from mails & notes is adressed

- [x] Check exact POWER8 version

- [x] Check if all comments in powerpoint are resolved

- [x] Summary: NUMA

- [x] Remove 'charts' in slide master

- [x] Summary Slide: Multi-core

**Comment by flxw** [comment]
Auf Chart 18 sind No Prefetching Linien nicht immer gestrichtelt und das verwirrt etwas. Auf der Slide davor war das nämich der Fall

**Comment by flxw** [comment]
Auf Folie 7 fehlen die Quellen für das Intel Architektur Bild

**Comment by flxw** [comment]
liest sich als potenzielle Angriffsstelle. Columns sind doch Dictionary Encoded usw, was soll man noch komprimieren? Oder ist hardwarebeschleunigte Kompression gemeint? Das ist ganz interessant, aber sprengt ggf den Rahmen, POWER hat sogar so etwas eingebaut

**Comment by danthe96** [comment]
Ja geht um Hardware-Kompression, passt gut zum Thema der anderen Gruppe

**Comment by MasterCarl** [comment]
Closing due to successful delivery of the presentation!
